checks:
    php:
        code_rating:        true
        duplication:        true
        no_exit:            false
        no_global_keyword:  false
        one_class_per_file: false
filter:
    dependency_paths:
        - wordpress/
    excluded_paths:
        - tests/*
        - bin/*
        - languages/*
tools:
    php_code_sniffer:
        config:
            standard: "WordPress"

build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            tests:
                override:
                    - php-scrutinizer-run