checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
        - bin/*
        - languages/*
tools:
    php_code_sniffer:
        config:
            standard: "WordPress"
build: false
