language: php
sudo: false

php:
    - 5.3
    - 5.4
    - 5.6
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=3.7 WP_MULTISITE=0

matrix:
  exclude:
    - php: 5.6
      env: WP_VERSION=3.7 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=3.7 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
